version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/library/mkdocs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/library/openssh-example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/library/plex-example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/library/openssh-example"
    schedule:
      interval: "weekly"
