name: Identify Matrix object

on:
  workflow_dispatch:
  push:

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix_object}}
    steps:
      - name: Checkout directory
        uses: actions/checkout@v3
      - name: Creat Matrix object
        id: matrix
        shell: pwsh
        run: |
          $matrix = [pscustomobject]@{}
          $directories = [System.Collections.ArrayList]@()
          Get-ChildItem -Path $PWD -Recurse -Include Dockerfile | Select-Object -Property DirectoryName | Foreach-Object {$directories.Add($_.DirectoryName)} | Out-Null
          $matrix | Add-Member -MemberType NoteProperty -Name "projects" -Value $directories..split('/')[-1]
          $mat_object = $matrix | ConvertTo-Json -Compress
          Add-Content -Path $Env:GITHUB_OUTPUT -Value "matrix_object=$mat_object"


  docker:
    runs-on: ubuntu-latest
    needs: create-matrix
    strategy:
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Print current path
        run: |
          echo ${{ matrix.projects }}


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/${{ matrix.projects }}:latest
