name: Identify Matrix object

on:
  workflow_dispatch:
  push:

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Display the current path
        shell: pwsh
        run: |
         $bla = 1 + 4
         $bla
