name: Identify Matrix object

on:
  workflow_dispatch:
  push:

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix_object }}
    steps:
      - name: Checkout directory
        uses: actions/checkout@v3
      - name: Create Matrix object
        id: matrix
        shell: pwsh
        run: |
          $matrix = [pscustomobject]@{}
          $directories = [System.Collections.ArrayList]@()
          Get-ChildItem -Path $PWD -Recurse -Depth 2 -Include Dockerfile | Select-Object -Property DirectoryName | Foreach-Object {$directories.Add($_.DirectoryName.split('/')[-1])} | Out-Null
          $matrix | Add-Member -MemberType NoteProperty -Name "projects" -Value $directories
          $mat_object = $matrix | ConvertTo-Json -Compress
          Add-Content -Path $Env:GITHUB_OUTPUT -Value "matrix_object=$mat_object"
          $mat_object

  create-submodule-matrix:
    runs-on: ubuntu-latest
    needs: create-matrix
    outputs:
      matrix: ${{ steps.matrix.outputs.submodule_matrix_object }}
    steps:
      - name: Checkout directory
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Create Matrix object
        id: matrix
        shell: pwsh
        run: |
          $matrix_submodules = [pscustomobject]@{}
          $directories = [System.Collections.ArrayList]@()
          Get-ChildItem -Path $PWD -Recurse -Depth 2 -Include Dockerfile | Select-Object -Property DirectoryName | Foreach-Object {$directories.Add($_.DirectoryName.split('/')[-1])} | Out-Null
          $directories = $directories | Where-Object { ${{ fromJSON(needs.create-matrix.outputs.matrix) }}.projects -notcontains $_ }
          $matrix | Add-Member -MemberType NoteProperty -Name "projects" -Value $directories
          $mat_object = $matrix | ConvertTo-Json -Compress
          Add-Content -Path $Env:GITHUB_OUTPUT -Value "submodule_matrix_object=$mat_object"
          $mat_object
