name: Publish Private Documentation

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: docker-image-registry-rg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy to Azure Container Instances"
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          dns-name-label: url-for-container
          image: dockerimageregistrycodingislove.azurecr.io/taagech9/mkdocs:v0.0.1-dev-0eb7241
          cpu: 1 #Optional
          memory: 0.1 #Optional
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: mkdocs-container
          location: "west us"
