on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image you would like to deploy'
        required: true
        default: 'taagech9/mkdocs'
      image_version:
        description: 'Which version of the Docs would you like to publish'
        required: true
        default: '0.0.1'
  push:

name: Publish Private Documentation

env:
  RESOURCE_GROUP: docker-image-registry-rg


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ env.RESOURCE_GROUP }}
            dns-name-label: url-for-container
            image: dockerimageregistrycodingislove.azurecr.io/${ github.event.input.image_name }}:${{ github.event.input.image_version }}
            cpu: 1   #Optional
            memory: 0.1   #Optional
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: ${{ github.event.input.image_name }}-${{ github.event.input.image_version }}-container
            location: 'west us'
